#!/usr/bin/env python3
"""Convert the supplied Triforce GIF to the tiny early-boot RLE stream."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


SIZE = 96
BLACK_THRESHOLD = 8


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)


def encode_frame(frame: Image.Image) -> bytes:
    image = frame.convert("RGB").resize((SIZE, SIZE), Image.Resampling.LANCZOS)
    pixels = image.load()
    output = bytearray()
    for y in range(SIZE):
        x = 0
        while x < SIZE:
            while x < SIZE and max(pixels[x, y]) <= BLACK_THRESHOLD:
                x += 1
            if x == SIZE:
                break
            start = x
            while x < SIZE and max(pixels[x, y]) > BLACK_THRESHOLD:
                x += 1
            output.extend((y, start, x - start))
            for column in range(start, x):
                value = rgb565(*pixels[column, y])
                output.extend((value & 0xFF, value >> 8))
    return bytes(output)


def write_header(source: Path, destination: Path) -> None:
    gif = Image.open(source)
    offsets = [0]
    stream = bytearray()
    durations = []
    for index in range(gif.n_frames):
        gif.seek(index)
        stream.extend(encode_frame(gif.copy()))
        offsets.append(len(stream))
        durations.append(int(gif.info.get("duration", 80)))

    lines = [
        "// Generated by platform/3ds/tools/generate-triforce-animation.py.",
        "// Do not edit by hand; regenerate from platform/3ds/assets/triforce.gif.",
        f"constexpr unsigned TriforceAnimationWidth = {SIZE};",
        f"constexpr unsigned TriforceAnimationHeight = {SIZE};",
        f"constexpr unsigned TriforceAnimationFrames = {gif.n_frames};",
        "constexpr uint32_t TriforceAnimationOffsets[] = {",
    ]
    for start in range(0, len(offsets), 8):
        lines.append("\t" + ", ".join(map(str, offsets[start : start + 8])) + ",")
    lines.extend(("};", "constexpr uint16_t TriforceAnimationDurations[] = {"))
    for start in range(0, len(durations), 12):
        lines.append("\t" + ", ".join(map(str, durations[start : start + 12])) + ",")
    lines.extend(("};", "constexpr uint8_t TriforceAnimationData[] = {"))
    for start in range(0, len(stream), 20):
        chunk = stream[start : start + 20]
        lines.append("\t" + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    lines.extend(("};", ""))
    destination.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    arguments = parser.parse_args()
    write_header(arguments.source, arguments.destination)


if __name__ == "__main__":
    main()
