#!/usr/bin/env python3
"""Prepare the native 3DS menu artwork and its compact bottom-screen stream."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


TOP_SIZE = (400, 240)
BOTTOM_SIZE = (320, 240)


def rgb565(pixel: tuple[int, int, int]) -> int:
    red, green, blue = pixel
    return ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)


def repeated_length(values: list[int], start: int) -> int:
    length = 1
    while (
        start + length < len(values)
        and length < 128
        and values[start + length] == values[start]
    ):
        length += 1
    return length


def encode_packbits(values: list[int]) -> bytes:
    """Encode RGB565 values as literal/repeated packets of at most 128 pixels."""
    output = bytearray()
    cursor = 0
    while cursor < len(values):
        repeated = repeated_length(values, cursor)
        if repeated >= 3:
            output.append(0x80 | (repeated - 1))
            output.extend((values[cursor] & 0xFF, values[cursor] >> 8))
            cursor += repeated
            continue

        literal_start = cursor
        cursor += repeated
        while cursor < len(values) and cursor - literal_start < 128:
            repeated = repeated_length(values, cursor)
            if repeated >= 3:
                break
            cursor += min(repeated, 128 - (cursor - literal_start))
        literal = values[literal_start:cursor]
        output.append(len(literal) - 1)
        for value in literal:
            output.extend((value & 0xFF, value >> 8))
    return bytes(output)


def write_header(image: Image.Image, destination: Path) -> None:
    values = [rgb565(pixel) for pixel in image.getdata()]
    stream = encode_packbits(values)
    lines = [
        "// Generated by platform/3ds/tools/generate-menu-screens.py.",
        "// Do not edit by hand; regenerate from platform/3ds/assets/menu-bottom.png.",
        f"constexpr unsigned MenuBottomWidth = {BOTTOM_SIZE[0]};",
        f"constexpr unsigned MenuBottomHeight = {BOTTOM_SIZE[1]};",
        f"constexpr unsigned MenuBottomPixelCount = {len(values)};",
        "constexpr uint8_t MenuBottomData[] = {",
    ]
    for start in range(0, len(stream), 20):
        chunk = stream[start : start + 20]
        lines.append("\t" + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    lines.extend(("};", ""))
    destination.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("top_source", type=Path)
    parser.add_argument("bottom_source", type=Path)
    parser.add_argument("story_source", type=Path)
    parser.add_argument("top_output", type=Path)
    parser.add_argument("bottom_output", type=Path)
    parser.add_argument("story_output", type=Path)
    parser.add_argument("header_output", type=Path)
    args = parser.parse_args()

    top_source = Image.open(args.top_source).convert("RGB")
    top = top_source.copy() if top_source.size == TOP_SIZE else top_source.resize(
        TOP_SIZE, Image.Resampling.LANCZOS
    )
    bottom = Image.open(args.bottom_source).convert("RGB").resize(
        BOTTOM_SIZE, Image.Resampling.LANCZOS
    )
    story_source = Image.open(args.story_source).convert("RGB")
    if story_source.size == TOP_SIZE:
        # Preserve native 3DS artwork pixel-for-pixel.
        story = story_source.copy()
    else:
        # High-contrast pixel text benefits from a reducing prepass followed
        # by bilinear filtering when a larger source needs minification.
        story = story_source.resize(
            TOP_SIZE, Image.Resampling.BILINEAR, reducing_gap=2.0
        )
    args.top_output.parent.mkdir(parents=True, exist_ok=True)
    args.bottom_output.parent.mkdir(parents=True, exist_ok=True)
    args.story_output.parent.mkdir(parents=True, exist_ok=True)
    args.header_output.parent.mkdir(parents=True, exist_ok=True)
    top.save(args.top_output, optimize=True)
    bottom.save(args.bottom_output, optimize=True)
    story.save(args.story_output, optimize=True)
    write_header(bottom, args.header_output)


if __name__ == "__main__":
    main()
