#!/usr/bin/env python3
"""Prepare the native lower-screen HUD and pause-menu artwork."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


BOTTOM_SIZE = (320, 240)
PAUSE_LOGO_SIZE = (213, 163)


def argb1555(pixel: tuple[int, int, int, int]) -> int:
    red, green, blue, alpha = pixel
    if alpha < 128:
        return 0
    return 0x8000 | ((red >> 3) << 10) | ((green >> 3) << 5) | (blue >> 3)


def repeated_length(values: list[int], start: int) -> int:
    length = 1
    while (
        start + length < len(values)
        and length < 128
        and values[start + length] == values[start]
    ):
        length += 1
    return length


def encode_packbits(values: list[int]) -> bytes:
    """Encode 16-bit values as literal/repeated packets of at most 128 pixels."""
    output = bytearray()
    cursor = 0
    while cursor < len(values):
        repeated = repeated_length(values, cursor)
        if repeated >= 3:
            output.append(0x80 | (repeated - 1))
            output.extend((values[cursor] & 0xFF, values[cursor] >> 8))
            cursor += repeated
            continue

        literal_start = cursor
        cursor += repeated
        while cursor < len(values) and cursor - literal_start < 128:
            repeated = repeated_length(values, cursor)
            if repeated >= 3:
                break
            cursor += min(repeated, 128 - (cursor - literal_start))
        literal = values[literal_start:cursor]
        output.append(len(literal) - 1)
        for value in literal:
            output.extend((value & 0xFF, value >> 8))
    return bytes(output)


def fitted(source: Image.Image, size: tuple[int, int]) -> Image.Image:
    image = source.convert("RGBA")
    image.thumbnail(size, Image.Resampling.NEAREST)
    return image


def write_header(images: list[tuple[str, Image.Image]], destination: Path) -> None:
    lines = [
        "// Generated by platform/3ds/tools/prepare-game-ui.py.",
        "// Do not edit by hand; regenerate from the supplied UI and pinned mod assets.",
    ]
    for name, image in images:
        values = [argb1555(pixel) for pixel in image.convert("RGBA").getdata()]
        stream = encode_packbits(values)
        lines.extend(
            (
                f"constexpr unsigned {name}Width = {image.width};",
                f"constexpr unsigned {name}Height = {image.height};",
                f"constexpr unsigned {name}PixelCount = {len(values)};",
                f"constexpr uint8_t {name}Data[] = {{",
            )
        )
        for start in range(0, len(stream), 20):
            chunk = stream[start : start + 20]
            lines.append("\t" + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
        lines.extend(("};", ""))
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines), encoding="utf-8")


def make_pause_logo(source_path: Path) -> Image.Image:
    source = Image.open(source_path).convert("RGBA")
    pixels = list(source.getdata())
    keyed = []
    for red, green, blue, alpha in pixels:
        keyed.append((red, green, blue, 0 if red >= 254 and green >= 254 and blue >= 254 else alpha))
    source.putdata(keyed)
    bounds = source.getbbox()
    if bounds is None:
        raise ValueError(f"Pause logo has no visible pixels: {source_path}")
    logo = source.crop(bounds)
    scale = min(PAUSE_LOGO_SIZE[0] / logo.width, PAUSE_LOGO_SIZE[1] / logo.height)
    logo = logo.resize(
        (max(1, round(logo.width * scale)), max(1, round(logo.height * scale))),
        Image.Resampling.LANCZOS,
    )
    return logo


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("frame_source", type=Path)
    parser.add_argument("pause_logo_source", type=Path)
    parser.add_argument("mod_source", type=Path)
    parser.add_argument("frame_output", type=Path)
    parser.add_argument("pause_logo_output", type=Path)
    parser.add_argument("header_output", type=Path)
    args = parser.parse_args()

    frame = Image.open(args.frame_source).convert("RGBA")
    if frame.size != BOTTOM_SIZE:
        frame = frame.resize(BOTTOM_SIZE, Image.Resampling.NEAREST)

    graphics = args.mod_source / "graphics"
    sprites = args.mod_source / "sprites"
    images: list[tuple[str, Image.Image]] = [("BottomGameFrame", frame)]

    for name, filename in (
        ("BottomFaceNormal", "STFST00.png"),
        ("BottomFaceBlue", "BRNST00.png"),
        ("BottomFaceRed", "RRNST00.png"),
    ):
        images.append(
            (
                name,
                Image.open(graphics / filename)
                .convert("RGBA")
                .resize((36, 44), Image.Resampling.NEAREST),
            )
        )

    for name, filename in (
        ("BottomHeartEmpty", "HARTEMTY.png"),
        ("BottomHeartQuarter", "HART1QRT.png"),
        ("BottomHeartHalf", "HARTHALF.png"),
        ("BottomHeartThreeQuarter", "HART3QRT.png"),
        ("BottomHeartFull", "HARTFULL.png"),
    ):
        images.append((name, fitted(Image.open(graphics / filename), (9, 10))))

    for name, filename in (
        ("BottomCounterRupee", "RUPEEBAG.png"),
        ("BottomCounterKey", "KEYMENU.png"),
        ("BottomCounterBomb", "BOMMMENU.png"),
    ):
        images.append((name, fitted(Image.open(sprites / filename), (9, 10))))

    item_assets = (
        ("BottomItemSword", "sprites/SWD1A0.png"),
        ("BottomItemBoomerang", "graphics/BOOMHUD1.png"),
        ("BottomItemBow", "sprites/AROWA0.png"),
        ("BottomItemBomb", "sprites/BOMBA0.png"),
        ("BottomItemCandle", "sprites/CNDLA0.png"),
        ("BottomItemWhistle", "sprites/WSTLA0.png"),
        ("BottomItemWand", "sprites/WANDA0.png"),
        ("BottomItemPotion", "sprites/POT1A0.png"),
        ("BottomItemMeat", "sprites/MEATA0.png"),
        ("BottomItemLadder", "sprites/LADRA0.png"),
        ("BottomItemRaft", "sprites/RAFTA0.png"),
        ("BottomItemBook", "sprites/BOOKA0.png"),
        ("BottomItemRing", "sprites/RINGA0.png"),
        ("BottomItemBracelet", "sprites/PWRBA0.png"),
        ("BottomItemLionKey", "sprites/KEEEA0.png"),
        ("BottomItemTriforce", "graphics/TRI8.png"),
    )
    for name, filename in item_assets:
        images.append((name, fitted(Image.open(args.mod_source / filename), (24, 28))))

    pause_logo = make_pause_logo(args.pause_logo_source)
    args.frame_output.parent.mkdir(parents=True, exist_ok=True)
    args.pause_logo_output.parent.mkdir(parents=True, exist_ok=True)
    frame.save(args.frame_output, optimize=True)
    pause_logo.save(args.pause_logo_output, optimize=True)
    write_header(images, args.header_output)


if __name__ == "__main__":
    main()
